spring:
  mvc:
    servlet:
      path: /api
  application:
    name: chat-socket
  datasource:
    url: jdbc:postgresql://localhost:5432/chat-socket-db
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8089

chat-socket:
  access-token-secret: b36f4b7a666a2333a289666f390d0cc78b574ab7597faabd8d7722c1dfd2ca01b6c3466b779b921ab8c0e1bb86f5c72ac601c2395dfd9872cccda8046610f68a
  access-token-ttl: 15 # minutes
  refresh-token-ttl: 14 # days