spring:
  mvc:
    servlet:
      path: /api
  application:
    name: chat-socket
  datasource:
    url: jdbc:postgresql://localhost:5432/chat-socket-db
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8089

chat-socket:
  access-token-secret: secret-key
  access-token-ttl: 15 # minutes
  refresh-token-ttl: 14 # days
  client-url: http://localhost:3000